#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
int g_argc; char **g_argv;
static void main_pipeline(void){

    if (g_argc < 3) {
        fprintf(stderr, "usage: python_to_c.exe <input.py> <output.c>\n");
        exit(2);
    }
    FILE *in = fopen(g_argv[1], "rb");
    if (!in) exit(4);
    FILE *out = fopen(g_argv[2], "wb");
    if (!out) { fclose(in); exit(4); }

    fprintf(out, "/* Generated by the base axi Python pipeline (Pure Axi). */\n");
    fprintf(out, "#include <stdio.h>\n");
    fprintf(out, "int main(void) {\n");

    char line[1024];
    while (fgets(line, sizeof(line), in)) {
        char* p = strstr(line, "print(");
        if (p) {
            p += 6; // skip "print("
            if (*p == '"') {
                char* end = strchr(p + 1, '"');
                if (end) {
                    *end = '\0';
                    fprintf(out, "    puts(\"%s\");\n", p + 1);
                }
            } else if (*p >= '0' && *p <= '9') {
                int val = atoi(p);
                fprintf(out, "    printf(\"%%d\\n\", %d);\n", val);
            }
        }
    }
    fprintf(out, "    return 0;\n}\n");
    fclose(in);
    fclose(out);

}
static void start(void){

    // Start of compilation

}
int main(int argc,char**argv){g_argc=argc;g_argv=argv;
start();
main_pipeline();
return 0;}
